

language: node_js
node_js:
  - "13"

script:
  - npm test
  - NODE_ENV=production npm run build

before_deploy:
  - npm install -g firebase-tools

deploy:
  # Deploy on test env
  - provider: firebase
    edge: true
    project: test
    on:
      branche: develop

  # Deploy on production env
  - provider: firebase
    edge: true
    project: prod
    on:
      branche: master
