language: node_js
node_js:
  - "13"

env:
  NODE_ENV=test
  SERVER_ENV=test

before_script:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      export SERVER_ENV=production;
    fi

script:
  - npm test
  - NODE_ENV=production npm run build

before_deploy:
  - npm install -g firebase-tools
  - git config --local user.name "Vadasz Laszlo"
  - git config --local user.email "maxinteger@gmail.com"
  - export TRAVIS_TAG=v$(date +'%Y-%m-%d')
  - git tag $TRAVIS_TAG

deploy:
  # Deploy on test env
  - provider: firebase
    edge: true
    project: test
    on:
      branche: develop

  # Deploy on production env
  - provider: firebase
    edge: true
    project: prod
    on:
      branche: master

  # Deploy on production env
  - provider: releases
    edge: true
    on:
      branche: master
